version: 1.0.{build}
image: Visual Studio 2015
install:
        - set QTDIR=C:\Qt\5.13.2\mingw73_64
        - set PATH=%PATH%;%QTDIR%\bin;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
build_script:
        - qmake CONFIG+=static test.pro
        - mingw32-make
        - C:/Qt/5.13.2/mingw73_64/lib/libQt5Quick.a C:/Qt/5.13.2/mingw73_64/lib/libQt5Gui.a C:/Qt/5.13.2/mingw73_64/lib/libQt5Qml.a C:/Qt/5.13.2/mingw73_64/lib/libQt5Network.a C:/Qt/5.13.2/mingw73_64/lib/libQt5Core.a  -lmingw32 C:/Qt/5.13.2/mingw73_64/lib/libqtmain.a -lshell32 
        - dir release
artifacts:
        - path: release/test.exe
        - path: release/test2.exe
        - path: Makefile.Release
