version: 1.0.{build}
image: Visual Studio 2019
install:
        - set QTDIR=C:\Qt\5.13.2\mingw73_64
        - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
        - qmake test.pro
        - mingw64-make
        
