version: 1.0.{build}
image: Visual Studio 2015
install:
        - set QTDIR=C:\Qt\5.13.2\msvc2015_64
        - set PATH=%PATH%;%QTDIR%\bin;
build_script:
        - md build
        - cd build
        - qmake CONFIG+=static CONFIG+=qtquickcompiler -spec win32-msvc CONFIG+=release "..\test.pro"
        - msbuild test.vcxproj /p:Configuration=Release /p:Platform="x64" /p:VcpkgTriplet=x64-windows-static
artifacts:
        - path: build/release/*
        - path: Makefile.Release
