version: 1.0.{build}
image: Visual Studio 2015
install:
        - set QTDIR=C:\Qt\5.13.2\msvc2015_64
        - set PATH=%PATH%;%QTDIR%\bin;
build_script:
        - dir C:\Qt\
        - qmake CONFIG+=static CONFIG+=qtquickcompiler -spec win32-msvc CONFIG+=release test.pro
        - nmake
artifacts:
        - path: release/*
        - path: Makefile.Release
